webdev/tarefas/urls.py
from django.urls import path

from webdev.tarefas import views

app_name='tarefas'

urlpatterns=[
    path('', views.home, name='home'),
    path('<int:tarefa_id>', views.detalhe, name='detalhe'),
    path('apagar/<int:tarefa_id>', views.apagar, name='apagar'),
]

webdev/urls.py
from django.contrib import admin
from django.urls import path, include

from webdev.home_view import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('tarefas/', include('webdev.tarefas.urls'))
]

webdev/tarefas/models.py
from django.db import models

# Create your models here.

class Tarefa(models.Model):
    nome = models.CharField(max_length=128)
    feita = models.BooleanField(default=False)

webdev/tarefas/forms.py
from django.forms import ModelForm

from webdev.tarefas.models import Tarefa


class TarefaNovaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = ['nome']


class TarefaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = ['nome', 'feita']

webdev/tarefas/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from webdev.tarefas.forms import TarefaNovaForm, TarefaForm
from webdev.tarefas.models import Tarefa


def home(request):
    if request.method == 'POST':
        form = TarefaNovaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tarefas:home'))
        else:
            tarefas_pendentes = Tarefa.objects.filter(feita=False).all()
            tarefas_feitas = Tarefa.objects.filter(feita=True).all()
            return render(
                request, 'tarefas/home.html',
                {
                    'form': form,
                    'tarefas_pendentes': tarefas_pendentes,
                    'tarefas_feitas': tarefas_feitas,
                },
                status=400)
    tarefas_pendentes = Tarefa.objects.filter(feita=False).all()
    tarefas_feitas = Tarefa.objects.filter(feita=True).all()
    return render(request, 'tarefas/home.html',
                  {
                      'tarefas_pendentes': tarefas_pendentes,
                      'tarefas_feitas': tarefas_feitas,
                  }
                  )


def detalhe(request, tarefa_id):
    if request.method=='POST':
        tarefa = Tarefa.objects.get(id=tarefa_id)
        form = TarefaForm(request.POST, instance=tarefa)
        if form.is_valid():
            form.save()
    return HttpResponseRedirect(reverse('tarefas:home'))


def apagar(request, tarefa_id):
    if request.method == 'POST':
        Tarefa.objects.filter(id=tarefa_id).delete()
    return HttpResponseRedirect(reverse('tarefas:home'))

webdev/tarefas/templates/tarefas/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Tarefas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="mt-5">Lista de Tarefas</h1>
            <form action="{% url 'tarefas:home' %}" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Descreva sua tarefa"
                           aria-label="Descreva sua tarefa" aria-describedby="button-addon2" name="nome">
                    <button type="submit" class="btn btn-primary" id="button-addon2">Salvar</button>
                </div>
                <div class="form-text">{{ form.nome.errors }}</div>
            </form>
            <h2 class="mt-5">Tarefas Pendentes</h2>

            {% for tarefa in tarefas_pendentes %}
                <form action="{% url 'tarefas:detalhe' tarefa_id=tarefa.id %}" method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Descreva sua tarefa" required="required"
                               aria-label="Descreva sua tarefa" name="nome" value="{{ tarefa.nome }}">
                        <input type="hidden" value="checked" name="feita">
                        <button type="submit" class="btn btn-success">Marcar como Feita</button>
                    </div>
                </form>
            {% endfor %}
            <h2 class="mt-5">Tarefas já Concluidas</h2>

            {% for tarefa in tarefas_feitas %}
                <div class="row">
                    <div class="col-2">
                         <form action="{% url 'tarefas:apagar' tarefa_id=tarefa.id %}" method="post">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <button type="submit" class="btn btn-danger">Apagar</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-10">
                        <form action="{% url 'tarefas:detalhe' tarefa_id=tarefa.id %}" method="post">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Descreva sua tarefa"
                                       required="required"
                                       aria-label="Descreva sua tarefa" name="nome" value="{{ tarefa.nome }}">
                                <button type="submit" class="btn btn-warning">Marcar como Pendente</button>
                            </div>
                        </form>
                    </div>

                </div>

            {% endfor %}
        </div>
    </div>
</div>

</body>
</html>